runtime: nodejs20

handlers:
  # Archivos estáticos (js, css, imágenes, etc.)
  - url: /(.*\.(js|css|ico|png|jpg|svg|json|txt|html))$
    static_files: build/\1
    upload: build/.*\.(js|css|ico|png|jpg|svg|json|txt|html)

  # Resto de rutas (React Router)
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
